/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SSJni */

#ifndef _Included_SSJni
#define _Included_SSJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SSJni
 * Method:    scanDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSJni_scanDevice
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
